name       : dvtm
version    : '0.15'
release    : 5
source     :
    - https://github.com/martanne/dvtm/archive/refs/tags/v0.15.tar.gz : 496eada13d8abaa8d772279746f78b0c6fed11b560599490f3e70ebc21197bf0
homepage   : https://www.brain-dump.org/projects/dvtm
license    : MIT
component  : system.utils
summary    : Tiling window manager for the console
description: |
    dvtm brings the concept of tiling window management to the console.
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    # Terminfo is mainlined in ncurses.
    rm -rf $installdir/usr/share/terminfo
